# Generated by Django 4.2.6 on 2023-10-29 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_audit', '0002_empleado_tarea_proyecto_notificacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='tareas',
        ),
        migrations.AddField(
            model_name='tarea',
            name='proyecto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='employee_audit.proyecto'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
