# Generated by Django 4.2.6 on 2023-10-29 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_audit', '0004_mensaje_alter_empleado_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='mensaje',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='employee_audit.mensaje'),
        ),
    ]
