# Generated by Django 4.2.6 on 2023-11-02 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_audit', '0006_alter_mensaje_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='empleados',
            field=models.ManyToManyField(to='employee_audit.empleado', verbose_name='Empleados'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='tareas'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='employee_audit.proyecto'),
        ),
    ]
