# Generated by Django 4.2.6 on 2023-11-02 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_audit', '0007_alter_tarea_empleados_alter_tarea_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Tareas'),
        ),
    ]
