# Generated by Django 4.2.6 on 2023-11-02 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_audit', '0008_alter_tarea_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='empleados',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='nombre',
        ),
        migrations.AddField(
            model_name='tarea',
            name='descripcion',
            field=models.TextField(default='Tarea sin descripción', verbose_name='Descripción de la tarea'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee_audit.proyecto'),
        ),
        migrations.CreateModel(
            name='TareaXEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_audit.empleado')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_audit.tarea')),
            ],
            options={
                'verbose_name': 'Tarea por Empleado',
                'verbose_name_plural': 'Tareas por Empleados',
            },
        ),
    ]
